# Dimairport # city AIRPORT_ID	ORIGIN AIRPORT_CODE 	COUNTRY_CODE	COUNTRY_NAME	CITY_NAME
# DIMairline # AIRLINE_ID	UNIQUE_CARRIER_NAME	CARRIER_NAME	OVERALL  RATING 	LEGROOM	SEAT COMFORT	CUSTOMER SERVICE 	VALUE FOR MONEY	CHECK-IN AND BOARDING	FOOD AND BEVERAGE	IN-FLIGHT ENTERTAINMENT (WIFI, TV, FILMS)
# DIMYEAR   # AVERAGETEMPERATUREINDEGREESCELSIUS	MONTH	YEAR QUARTER	T_ID

library(dplyr)

#2017

setwd("C:\Users\MOLAP\Documents\R\AVIATION")

AVIATIONDATA_2017<-read.csv("ALL_CARRIER_2017.csv",header=T,na.strings = c(""),stringsAsFactors = T)
DF1_NEW_2017<- AVIATIONDATA_2017[order(AVIATIONDATA_2017$MONTH),]
DF1_NEW_2017<-filter(DF1_NEW_2017, ORIGIN_COUNTRY_NAME == "United States")
DF1_2017<- select(DF1_NEW_2017,PASSENGERS,AIRLINE_ID,CARRIER,CARRIER_NAME,UNIQUE_CARRIER_NAME,ORIGIN_COUNTRY,ORIGIN_COUNTRY_NAME,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_AIRPORT_ID,
                  DEST_COUNTRY,DEST_COUNTRY_NAME,DEST,DEST_CITY_NAME,DEST_AIRPORT_ID,YEAR,MONTH,QUARTER)


#2016 YEAR SPAIN DATA

AVIATIONDATA_2016<-read.csv("ALL_CARRIER_2016.csv",header=T,na.strings = c(""),stringsAsFactors = T)
DF1_NEW_2016<- AVIATIONDATA_2016[order(AVIATIONDATA_2016$MONTH),]
DF1_NEW_2016<-filter(DF1_NEW_2016, ORIGIN_COUNTRY_NAME == "United States")
DF1_2016<- select(DF1_NEW_2016,PASSENGERS,AIRLINE_ID,CARRIER,CARRIER_NAME,UNIQUE_CARRIER_NAME,ORIGIN_COUNTRY,
                  ORIGIN_COUNTRY_NAME,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_AIRPORT_ID,
                  DEST_COUNTRY,DEST_COUNTRY_NAME,DEST,DEST_CITY_NAME,DEST_AIRPORT_ID,YEAR,MONTH,QUARTER)

#2015 YEAR SPAIN DATA
AVIATIONDATA_2015<-read.csv("ALL_CARRIER_2015.csv",header=T,na.strings = c(""),stringsAsFactors = T)
DF1_NEW_2015<- AVIATIONDATA_2015[order(AVIATIONDATA_2015$MONTH),]
DF1_NEW_2015<-filter(DF1_NEW_2015, ORIGIN_COUNTRY_NAME == "United States")
DF1_2015<- select(DF1_NEW_2015,PASSENGERS,AIRLINE_ID,CARRIER,CARRIER_NAME,UNIQUE_CARRIER_NAME,ORIGIN_COUNTRY,ORIGIN_COUNTRY_NAME,
ORIGIN,ORIGIN_CITY_NAME,ORIGIN_AIRPORT_ID,
DEST_COUNTRY,DEST_COUNTRY_NAME,DEST,DEST_CITY_NAME,DEST_AIRPORT_ID,YEAR,MONTH,QUARTER)
Raw_DATA_AVIATION<-rbind(DF1_2015,DF1_2016,DF1_2017)

setwd("C:\Users\MOLAP\Documents\R")

write.csv(Raw_DATA_AVIATION, file = "Raw_DATA_AVIATION.csv",row.names=FALSE)






